// <auto-generated />
using CarRental.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRental.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260807181441_AddedMigration")]
    partial class AddedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRental.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Small, cheap to run — ideal for city driving and short trips.",
                            IsActive = true,
                            Name = "Economy"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Comfortable four-door cars with a separate boot.",
                            IsActive = true,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Higher driving position and more space — good for rough roads.",
                            IsActive = true,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Maximum passenger and luggage capacity for groups.",
                            IsActive = true,
                            Name = "Van"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Premium vehicles with high-end interiors and performance.",
                            IsActive = true,
                            Name = "Luxury"
                        });
                });

            modelBuilder.Entity("CarRental.Models.FuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Petrol"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Diesel"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Electric"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Hybrid"
                        });
                });

            modelBuilder.Entity("CarRental.Models.TransmissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TransmissionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Manual"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Automatic"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Semi-Automatic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
