// <auto-generated />
using System;
using CarRental.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRental.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901164108_AddedVehicle")]
    partial class AddedVehicle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRental.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Citroën"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Dacia"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Jaguar"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Jeep"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Lancia"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Land Rover"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "Lexus"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "Mini"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            Name = "Opel"
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            Name = "Seat"
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            Name = "Škoda"
                        },
                        new
                        {
                            Id = 28,
                            IsActive = true,
                            Name = "Smart"
                        },
                        new
                        {
                            Id = 29,
                            IsActive = true,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 30,
                            IsActive = true,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 31,
                            IsActive = true,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 32,
                            IsActive = true,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 33,
                            IsActive = true,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 34,
                            IsActive = true,
                            Name = "Volvo"
                        });
                });

            modelBuilder.Entity("CarRental.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Small, cheap to run — ideal for city driving and short trips.",
                            IsActive = true,
                            Name = "Economy"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Comfortable four-door cars with a separate boot.",
                            IsActive = true,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Higher driving position and more space — good for rough roads.",
                            IsActive = true,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Maximum passenger and luggage capacity for groups.",
                            IsActive = true,
                            Name = "Van"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Premium vehicles with high-end interiors and performance.",
                            IsActive = true,
                            Name = "Luxury"
                        });
                });

            modelBuilder.Entity("CarRental.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Bluetooth"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "GPS Navigation"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Parking Sensors"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Reversing Camera"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Cruise Control"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Heated Seats"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Leather Seats"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Sunroof"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Roof Rack"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Tow Bar"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Child Seat"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "USB Charging"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Apple CarPlay"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Android Auto"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "Winter Tyres"
                        });
                });

            modelBuilder.Entity("CarRental.Models.FuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Petrol"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Diesel"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Electric"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Hybrid"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Plug-in Hybrid"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "LPG"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = false,
                            Name = "Mild Hybrid"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = false,
                            Name = "CNG"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = false,
                            Name = "Range Extender"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = false,
                            Name = "Hydrogen"
                        });
                });

            modelBuilder.Entity("CarRental.Models.TransmissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TransmissionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Manual"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Automatic"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Semi-Automatic"
                        });
                });

            modelBuilder.Entity("CarRental.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<decimal?>("EngineSize")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForRent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("bit");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationPlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("RentalPricePerDay")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("TransmissionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("RegistrationPlate")
                        .IsUnique();

                    b.HasIndex("TransmissionTypeId");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CarRental.Models.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("CarRental.Models.Vehicle", b =>
                {
                    b.HasOne("CarRental.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.Models.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.Models.TransmissionType", "TransmissionType")
                        .WithMany()
                        .HasForeignKey("TransmissionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.Models.VehicleModel", "VehicleModel")
                        .WithMany()
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FuelType");

                    b.Navigation("TransmissionType");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("CarRental.Models.VehicleModel", b =>
                {
                    b.HasOne("CarRental.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });
#pragma warning restore 612, 618
        }
    }
}
